# Generated by Django 3.1.5 on 2021-03-29 00:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0002_description_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('descriptioin', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('period', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
