# Generated by Django 3.1.5 on 2021-03-29 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0003_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='descriptioin',
            new_name='description',
        ),
    ]
