# Generated by Django 3.1.5 on 2021-03-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greeting', '0004_auto_20210328_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='period',
            field=models.DateField(blank=True),
        ),
    ]
