# Generated by Django 3.1.1 on 2020-09-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200929_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Above to Read Blog Post', max_length=255),
        ),
    ]
