# Generated by Django 3.1.1 on 2020-09-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Below to Read Blog Post', max_length=255),
        ),
    ]
