# Generated by Django 3.1.1 on 2020-11-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201101_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_thumbnails'),
        ),
    ]
