# Generated by Django 3.1.1 on 2020-11-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_thumbnail_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
