# Generated by Django 3.1.1 on 2020-11-26 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
